In [2]:
#!pip install joblib

In [54]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
import pandas as pd
plt.style.use("fivethirtyeight")

In [78]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta # learning rate
        self.epochs = epochs # iterations
    
    def _z_outcome(self, inputs, weights):
        return np.dot(inputs, weights)
    
    def activation_function(self, z):
        return np.where(z > 0, 1, 0)
    
    def fit(self,X,y):
        self.X = X
        self.y = y
        
        X_with_bais = np.c_[self.X, -np.ones((len(X),1))]
        print(f"X with bais: \n{X_with_bais}")
        
        for epoch in range(self.epochs):
            
            print("-----"*5)
            print(f"for epoch >> {epoch + 1}")
            print("-----"*5)
            z = self._z_outcome(X_with_bais, self.weights)
            y_hat = self.activation_function(z)
            
            print(f"predicted value after the forward pass : \n{y_hat}")
            
            self.error = self.y - y_hat
            
            print(f"error: \n{self.error}")
            
            # w_new = w_old + n * X_transpose * error --> Backpropagations
            self.weights = self.weights + self.eta * np.dot(X_with_bais.T , self.error)
            
            print(f"updated weights after epoch: {epoch + 1}/{self.epochs} : \n {self.weights}")
            
            print(f"##"*10)
            
    def predict(self, X):
        
        X_with_bais = np.c_[X, -np.ones((len(X),1))]
        z = self._z_outcome(X_with_bais, self.weights)
        
        return self.activation_function(z)

In [79]:
OR = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y": [0,1,1,1]
}

df_OR = pd.DataFrame(OR)

In [80]:
df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [81]:
def prepare_data(df, target_col="y"):
    X = df.drop(target_col, axis = 1)
    y= df[target_col]
    
    return X, y 

In [82]:
X , y = prepare_data(df_OR)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [83]:
X , y = prepare_data(df_OR)

ETA = 0.1
EPOCHS = 10

model_or = Perceptron(eta = ETA, epochs = EPOCHS)

model_or.fit(X,y)

X with bais: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
-------------------------
for epoch >> 1
-------------------------
predicted value after the forward pass : 
[1 0 1 1]
error: 
0   -1
1    1
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 1/10 : 
 [ 1.45843449e-04  9.99514241e-02 -6.49549621e-06]
####################
-------------------------
for epoch >> 2
-------------------------
predicted value after the forward pass : 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10 : 
 [0.00014584 0.09995142 0.0999935 ]
####################
-------------------------
for epoch >> 3
-------------------------
predicted value after the forward pass : 
[0 0 0 1]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10 : 
 [ 0.10014584  0.19995142 -0.1000065 ]
####################
-------------------------
for epoch >> 4
-------------------------
predicted value after the f

In [71]:
model_or.predict(X=[[1,1]])

array([0])

In [30]:
obj = Perceptron(eta=0.01, epochs = 10)

In [31]:
obj.eta , obj.epochs

(0.01, 10)

In [32]:
obj.weights

array([-1.09006992e-04, -2.08187008e-04,  3.33945850e-05])

In [35]:
X = np.ones((4,2))
y = np.ones((4,1))

In [36]:
obj.fit(X,y)

X with bais: 
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]


In [40]:
z = -31
np.where(z > 0, 1, 0)

array(0)

In [5]:
 np.random.randn(3)

array([ 0.46446569, -1.0422912 , -0.26744867])

In [7]:
np.ones((4,1))

array([[1.],
       [1.],
       [1.],
       [1.]])

In [11]:
X = np.ones((4,2))
np.c_[X, -np.ones((len(X),1))]

array([[ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.]])