In [2]:
#!pip install joblib

In [3]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np

plt.style.use("fivethirtyeight")

In [24]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta # learning rate
        self.epochs = epochs # iterations
        
    def fit(self,X,y):
        self.X = X
        self.y = y
        
        X_with_bais = np.c_[self.X, -np.ones((len(X),1))]
        print(f"X with bais: \n{X_with_bais}")

In [30]:
obj = Perceptron(eta=0.01, epochs = 10)

In [31]:
obj.eta , obj.epochs

(0.01, 10)

In [32]:
obj.weights

array([-1.09006992e-04, -2.08187008e-04,  3.33945850e-05])

In [35]:
X = np.ones((4,2))
y = np.ones((4,1))

In [36]:
obj.fit(X,y)

X with bais: 
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]


In [5]:
 np.random.randn(3)

array([ 0.46446569, -1.0422912 , -0.26744867])

In [7]:
np.ones((4,1))

array([[1.],
       [1.],
       [1.],
       [1.]])

In [11]:
X = np.ones((4,2))
np.c_[X, -np.ones((len(X),1))]

array([[ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.]])